version: "3"

services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/app
    environment:
      BOT_NOTIFY_WEBHOOK_URL: "https://discord.com/api/webhooks/..."
      BOT_ERROR_WEBHOOK_URL: "https://discord.com/api/webhooks/..."
      BOT_REFRESH_FREQUENCY: "10s"
